version: '3'

services:

  pkgr:
    depends_on:
      - pkgr-postgres
    image: monotek/pkgr-docker-compose:pkgr
    restart: always
    volumes:
      - data-pkgr:/home/pkgr

  pkgr-postgres:
    image: monotek/pkgr-docker-compose:pkgr-postgres
    restart: always

volumes:
  data-pkgr:
    driver: local
